푸시 알림 관련 테이블 및 api 수정
Hous-Release/hous-server pull request #108
Opened 2022-09-18 08:43 UTC by orijoon98

## ✒️ 관련 이슈번호

- Closes #53 
## 🔑 Key Changes

1. 푸시 알림 관련 테이블 및 api 수정

## 📢 To Reviewers
- 마지막 커밋만 봐주세요!

2022-09-19 15:37 UTC, hyejungg requested changes
궁금한 점이 있어서 RC 합니다 !

2022-09-19 15:37 UTC, hyejungg commented on src/main/java/hous/server/service/user/UserServiceUtils.java
> +                request.getBadgePushStatus() == user.getSetting().getBadgePushStatus()) {
기존 상태와의 중복 여부를 확인하려면 `||`를 해줘야 하는게 아닌지요 ?! 이렇게 되면 6개 중 4개는 기존과 중복, 2개는 다르게면 exception이 안들어가지 않나?! 싶네요?!

2022-09-19 15:41 UTC, orijoon98 commented on src/main/java/hous/server/service/user/UserServiceUtils.java
> +                request.getBadgePushStatus() == user.getSetting().getBadgePushStatus()) {
버튼이 토글버튼, 라디오 버튼이라 한가지 상태값이 변경될때마다 모든 상태값을 담아서 요청을 보내는 형태라서
6가지 상태중 한가지가 달라야 정상적인 요청이라서 6가지 상태값이 모두 중복인지 체크해주는 방식입니다!

2022-09-19 15:41 UTC, orijoon98 commented on src/main/java/hous/server/service/user/UserServiceUtils.java
> +                request.getBadgePushStatus() == user.getSetting().getBadgePushStatus()) {
모두 중복인경우 에러를 던지기 위해 위 방법으로 검증합니당

2022-09-19 15:48 UTC, hyejungg commented on src/main/java/hous/server/service/user/UserServiceUtils.java
> +                request.getBadgePushStatus() == user.getSetting().getBadgePushStatus()) {
put 메소드로 받기 때문에 요 방식으로 돌리는건가요 ?!

2022-09-20 05:24 UTC, hyejungg approved these changes

2022-09-20 05:28 UTC, merged