#128 [fix] slack 에러 알림 추가
Hous-Release/hous-server pull request #149
Opened 2022-09-30 09:05 UTC by hyejungg

## ✒️ 관련 이슈번호

- Closes #128

## 🔑 Key Changes

1. slack 에러 알림 추가했습니다

## 📢 To Reviewers
- 노션에 application-slack.yml은 노션에 넣어두었으니 따로 넣으세용

2022-10-03 06:26 UTC, orijoon98 commented
지금봤는데 브랜치명 / 이 빠졌다 ㅋㅋ!

2022-10-05 06:27 UTC, orijoon98 requested changes
몇가지만 반영하고 origin 브랜치 삭제하고 브랜치명 수정해서 다시 pr 올리면 될것같습니다~!!
슬랙 알림 예쁘게 오네요 고생하셨습니다아 😆

2022-10-05 06:27 UTC, orijoon98 commented on src/main/java/hous/server/common/util/JwtUtils.java
> +            log.error("JWT claims string is empty.", e);
다시 생각해보니 얘네 401 에러 던지게하는 부분이라 warn 으로 해야할것같아여!

2022-10-05 06:27 UTC, orijoon98 commented on src/main/java/hous/server/controller/advice/ControllerExceptionAdvice.java
>          return ErrorResponse.error(INTERNAL_SERVER_EXCEPTION);
보니깐 feign 도 500번대 에러 있는것같습니다!
그리고 별건 아니지만.. slackservice -> log / log -> slackserivce 순서 맞춰주면 어떨까여 ㅎㅋㅎㅋ

2022-10-05 06:27 UTC, orijoon98 commented on src/main/java/hous/server/service/slack/SlackService.java
> +    }
여기는 log.error(e.getMessage(), e) 방식으로 사용 안한 이유가 있을까여?!

2022-10-05 06:27 UTC, orijoon98 commented on src/main/java/hous/server/service/slack/SlackService.java
> +    }
메소드 분리 굿굿 👍

2022-10-05 09:10 UTC, hyejungg commented on src/main/java/hous/server/service/slack/SlackService.java
> +    }
저의 실수입니다 ~~ ㅎㅎ 반영하겠습니다 ~~

2022-10-05 09:12 UTC, closed without merging