성향 테스트 시 수정 성공 response와 함께 변경된 Personality color 전달하도록 수정
Hous-Release/hous-server pull request #186
Opened 2022-10-28 14:48 UTC by hyejungg

## ✒️ 관련 이슈번호

- Closes #185

## 🔑 Key Changes

1. 성향 테스트 시 수정 성공 response와 함께 변경된 Personality color 전달하도록 수정하였습니다.

## 📢 To Reviewers
- 기존에는 성향 테스트 시 새 값으로 변경까지만 했는데 color를 전달하도록 수정했습니다.
- 클라에서 테스트 후 바로 결과 화면을 보여줘야 하는데 그러려면 `GET /user/personality/test` 요청을 보내려면 color 값이 필요해서요!
   - 그런데 ... 지금 생각해보니 이렇게 되면 클라가 API 요청을 또 보내셔야 하는데 .... 
   - 뭔가 API 요청을 적게 보낼 수 있도록 return 시 보내달라고 할 것 같기도 합니다만 ..... 어떻게 생각하시나요 ?!

2022-10-28 15:32 UTC, orijoon98 approved these changes
200 메시지 업데이트 된 것만 반영하고 머지해주세요! 빠른 반영 감사합니다~!

2022-10-29 12:04 UTC, orijoon98 requested changes

2022-10-29 12:04 UTC, orijoon98 commented on src/main/java/hous/server/controller/user/UserController.java
>      )
말이 뭔가 어색해요...??

2022-10-29 12:04 UTC, orijoon98 commented on src/main/java/hous/server/service/user/dto/response/UpdatePersonalityColorResponse.java
> +}
이거 말고 성향 상세 정보 리스폰스로 주기로 한거 아니었나요?!

2022-10-29 12:06 UTC, hyejungg commented on src/main/java/hous/server/service/user/dto/response/UpdatePersonalityColorResponse.java
> +}
안드가 기능적 구현의 문제로 color로 전달받길 희망하였는데, 아요와 상의 후 알려달라고 했습니다! 
아요와 안드의 재논의 결과, put따로 get 따로 요청한다고 하여 color 값만 전달하도록 변경했습니다!

2022-10-29 12:07 UTC, hyejungg commented on src/main/java/hous/server/controller/user/UserController.java
>      )
성향테스트 결과를 수정 후 변경된 성향테스트 색상을 전달합니다. 로 하겠습니당 ~

2022-10-29 15:08 UTC, orijoon98 approved these changes
감사합니다~!

2022-10-29 16:39 UTC, merged