배지 관련 데이터 mongoDB 적용하는 방식으로 로직 수정
Hous-Release/hous-server pull request #313
Opened 2023-03-28 15:40 UTC by hyejungg

## ✒️ 관련 이슈번호

- Closes #304

## 🔑 Key Changes

1. BadgeServiceUtils, BadgeService 테스트 코드 추가 후 테스트 수행
2. 기존 redis 에서 카운터 하는 로직 삭제
3. badgeCounter entity 수정
   - 기존에는 ~CompleteCount 라는 필드명을 가졌는데 확장성을 고려하여 countType / count 로 변경했습니다.
4. 배지 획득 시 카운트 하는 로직 badgeCounter로 수정
   - 수정 후 테스트 코드 변경하여 수행

## 📢 To Reviewers
- 우선 todo 관련 배지 중 스케줄러에 의해 획득되는 배지는 테스트가 어려운 상황입니다. (참 잘했어요, 성실왕 호미, 투두 마스터)
  - 체크를 월 / 화 / 수 / 목 / 금 / 토 / 일 을 모두 해주고, 스케줄러 함수를 7번, 14번, 21번 호출하는 식으로 테스트 하려고 했으나
  - 체크 내부 로직에서 오늘 날짜만 체크할 수 있도록 되어 있어서 테스트가 어려웠습니다 ..... 
  - 이 부분은 논의가 필요해 보이네요 ... ㅠㅛㅠ 
    - 아쉬운대로 다른 카운트하여 획득하는 배지 (나도 날 잘 모르겠어, 우리집 기둥 호미) 미획득 시에 카운터 값을 확인하는 테스트 코드를 추가했습니다.

2023-03-28 16:28 UTC, orijoon98 requested changes
if, else 늪은.... 으악 저도 좀 더 고민해보겠습니다..

2023-03-28 16:28 UTC, orijoon98 commented on src/main/java/hous/server/domain/badge/BadgeCounterType.java
> +    TEST_SCORE_COMPLETE("TEST_SCORE_COMPLETE");
Key 와 Value 값 같게 사용하는거면 EnumModel 구현하지않고 그냥 enum으로만 써도 되지 않을까용?!
아니면 value에는 한글로 설명 적어놔도 좋을 것 같아요!

2023-03-28 16:28 UTC, orijoon98 commented on src/test/java/hous/server/service/badge/BadgeServiceUtilsTest.java
> +    public void hasBadge_exists_on_success() {
저희 테스트코드는 스네이크 케이스 사용하기로 한 것 같은데 예외가 존재하는걸까요..?!

2023-03-28 16:28 UTC, orijoon98 commented on src/test/java/hous/server/service/badge/BadgeServiceUtilsTest.java
> +    public void findBadgeById_by_not_found_exception() {
exception은 throw by 붙이기로 한 것 같습니다!

2023-03-28 16:29 UTC, orijoon98 commented
Todo 배지 관련 테스트는 서비스단 메서드들을 좀 더 분리해보고 나서 작성해보는건 어떨까요 ㅠㅠ
많이 무겁네요 서비스 메서드들...

2023-03-31 14:54 UTC, orijoon98 approved these changes

2023-03-31 16:50 UTC, orijoon98 commented on src/main/java/hous/server/domain/badge/BadgeCounterType.java
> +}
value 값 사용안하면 아예 지우고 @RequiredArgsConstructor(access = AccessLevel.PRIVATE) 이거랑 ("") 값 다 지우면 더 깔끔할 것 같은데 어떠신가요?!

2023-03-31 16:50 UTC, orijoon98 commented on src/test/java/hous/server/service/badge/BadgeServiceUtilsTest.java
> +    public void has_badge_un_exists_on_success() {
unexist 는 한단어니깐 붙여주는게 어떨까요?!

2023-04-01 15:06 UTC, hyejungg commented on src/main/java/hous/server/domain/badge/BadgeCounterType.java
> +}
좋은 의견입니다. 이전 커밋에 amend 하겠습니다!

2023-04-01 15:17 UTC, orijoon98 approved these changes
수고하셨습니당!!!

2023-04-01 15:19 UTC, merged