알림 서버 분리
Hous-Release/hous-server pull request #328
Opened 2023-04-28 19:24 UTC by orijoon98

## ✒️ 관련 이슈번호

- Closes #323

## 🔑 Key Changes

1. FCM 호출, Slack 알림 관련 서비스 알림 서버로 분리했습니다.
2. AWS SQS 도입해서 api 서버에서 메시지를 produce하고, 알림 서버에서 consume하도록 구현했습니다.
3. 모듈을 분리했지만 부분적으로 중복되는 코드들도 존재합니다. MessageDto, UserDelete, UserDeleteResponse 등이 있는데, common 모듈에 넣는 것은 common 모듈이 무거워 질 우려가 있어서 코드를 중복으로 작성하는 것으로 대체했습니다..!
4. CI/CD 관련한 부분도 전부 작성했습니다. 실제로 배포가 잘 되는지는 머지하면서 확인해보겠습니다!

## 📢 To Reviewers
- yml 파일에 많은 수정이 있습니다. api 서버에 yml 파일들이 존재하고, notification 서버에도 yml 파일들이 존재합니다. 관련해서 노션 Private 페이지에 전부 정리해뒀습니다!
- Github Secrets 는 api, notification 구별을 위해 APPLICATION_YML -> API_YML, NOTIFICATION_YML 과 같이 변경했습니다.

2023-04-30 15:20 UTC, hyejungg requested changes
모듈 분리 하시느라 고생 많으셨습니다 ㅠㅠ
몇가지 의견이 있어서 우선 RC 했습니다. 확인 부탁드려요!

2023-04-30 15:20 UTC, hyejungg commented on hous-notification/src/main/java/hous/notification/config/redis/RedisConfig.java
> +public class RedisConfig {
알림 서버에서 redis는 왜필요한거죠 ?!

2023-04-30 15:20 UTC, hyejungg commented on hous-notification/src/main/java/hous/notification/controller/advice/ControllerExceptionAdvice.java
> +			slackService.sendSlackMessageProductError(exception);
지금 저희가 관리해야할 서버 포인트가 기존은 api 서버 하나였지만, 알림서버로 2개가 됐는데요 ..... 

슬랙 알림에서 error stack 에 패키지명이 있어서 구분될 것 같긴하지만 이건 알림 서버다, api 서버다 한번에 볼 수 있도록 해야 할 것 같은데 어떻게 생각하시나요 .. ?!

2023-04-30 15:38 UTC, orijoon98 commented on hous-api/src/main/java/hous/api/config/sqs/dto/MessageDto.java
> +	private UserDeleteResponse userDeleteResponse;
너무 좋은 생각입니당.. 반영할게요!

2023-04-30 15:44 UTC, orijoon98 commented on hous-notification/src/main/java/hous/notification/controller/advice/ControllerExceptionAdvice.java
> +			slackService.sendSlackMessageProductError(exception);
호오.. 그러네요 반영해보겠습니다!!

2023-04-30 15:45 UTC, orijoon98 commented on hous-notification/src/main/java/hous/notification/config/redis/RedisConfig.java
> +public class RedisConfig {
fcm 전송을 실패 했을 때 로그아웃 처리하는 부분 때문에 필요했었는데, User 대신 fcm 토큰을 전달하게하고 실패할 경우에는 실패 메시지를 발행해서 다시 api 서버에서 로그아웃 처리하도록 수정할 계획이라 삭제 될 것 같습니당!

2023-05-01 07:12 UTC, orijoon98 commented
전체적으로 코드리뷰 반영했습니다! @hyejungg 
SQS 부가적인 설정 관련해서는 더 공부해보고 다른 이슈에서 진행해볼까 하는데 어떨까요?!

2023-05-01 08:43 UTC, hyejungg approved these changes
코드 리뷰 내용을 반영해주셔서 감사합니다. 고생하셨습니다 !! :D

2023-05-01 08:48 UTC, merged